name: "Release"

on:
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      name: "release"

  publish:
    name: "Publish"
    uses: ./.github/workflows/publish.yaml
    needs: [build]
    secrets: inherit
    with:
      name: "release"
    permissions:
      contents: write
      id-token: write

  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [publish]

    steps:
      - name: "Debug"
        continue-on-error: true
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.event.release.prerelease: ${{ github.event.release.prerelease }}"

      #- name: "Debug event.json"
      #  if: ${{ !github.event.act }}
      #  continue-on-error: true
      #  run: |
      #    cat "${GITHUB_EVENT_PATH}"

      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Update Latest Tag"
        if: ${{ !github.event.release.prerelease }}
        uses: cssnr/update-version-tags-action@latest
        continue-on-error: true
        with:
          major: false
          minor: false
          tags: latest
          #tag: ${{ github.ref_name }}

      - name: "Download Artifact"
        uses: actions/download-artifact@v6
        with:
          name: "release"
          path: dist

      - name: "List Artifacts"
        run: |
          ls -lAh dist
          ls dist | grep -- "-${{ github.ref_name }}-" > /dev/null

      - name: "Upload Release"
        uses: cssnr/upload-release-action@latest
        with:
          globs: dist/*

      - name: "Update Release Notes Action"
        continue-on-error: true
        uses: smashedr/update-release-notes-action@master
        with:
          location: tail

      - name: "Send Failure Notification"
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
