name: "Build"

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: false
        type: string
        default: dist

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    #permissions:
    #  contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Install"
        run: |
          python -m pip install -U pip
          python -m pip install -Ur requirements.txt

      - name: "Build"
        run: |
          python -m build

      - name: "List Artifacts"
        env:
          LS_DIR: ${{ inputs.path }}
        run: |
          ls -lAh ${LS_DIR}/*
          results="$(ls -lAh ${LS_DIR}/* | awk '{print $9" - "$5}')"
          markdown='Artifacts:\n```text\n'"${results}"'\n```'
          echo -e "${markdown}" >> $GITHUB_STEP_SUMMARY

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}
