name: "Release"

on:
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python 3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Build"
        run: |
          python -m pip install -U pip
          python -m pip install -Ur requirements.txt
          python -m build

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: dist

      - name: "Upload to Release"
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          file: dist/*

  pypi:
    name: "PyPI"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [build]
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory
    environment:
      name: pypi
      url: https://pypi.org/p/actions-tools

    steps:
      - name: "Download Artifact"
        uses: actions/download-artifact@v4
        with:
          name: release
          path: dist

      - name: "Debug"
        run: ls -lAh dist

      - name: "Publish to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
