name: "Release"

on:
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: write
    with:
      name: release

  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [build]
    permissions:
      contents: read
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/p/actions-tools

    steps:
      - name: "Download Artifact"
        uses: actions/download-artifact@v4
        with:
          name: release
          path: dist

      - name: "Debug"
        run: |
          echo ${GITHUB_REF_NAME}
          ls -lAh dist

      - name: "Upload to Release"
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          overwrite: true
          file_glob: true
          file: dist/*

      # TODO: Manually publish the package first
      #- name: "Publish to Test PyPI"
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with:
      #    repository-url: https://test.pypi.org/legacy/
