name: "Release"

on:
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    #permissions:
    #  contents: write
    with:
      name: release

  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [build]
    permissions:
      contents: write
      id-token: write
    environment:
      name: test
      url: https://test.pypi.org/p/actions-tools

    steps:
      #- name: "Debug event.json"
      #  if: ${{ always() }}
      #  run: |
      #    cat "${GITHUB_EVENT_PATH}"

      - name: "Download Artifact"
        uses: actions/download-artifact@v4
        with:
          name: release
          path: dist

      - name: "Debug Artifacts"
        run: |
          echo GITHUB_REF_NAME: "${GITHUB_REF_NAME}"
          echo github.ref_name: "${{ github.ref_name }}"
          ls -lAh dist

      - name: "Upload to Release"
        uses: svenstaro/upload-release-action@v2
        with:
          #overwrite: true
          file_glob: true
          file: dist/*

      - name: "Publish to Test PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          attestations: false

      #- name: "Update Release Notes"
      #  run: |
      #    echo update release notes with useful shit

      - name: "Send Failure Notification"
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
