name: "Release"

on:
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: write
    with:
      NAME: release

  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [build]
    environment:
      name: pypi
      url: https://pypi.org/p/actions-tools
    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory

    steps:
      - name: "Download Artifact"
        uses: actions/download-artifact@v4
        with:
          name: release
          path: dist

      - name: "Debug"
        run: |
          ls -lAh dist

      - name: "Upload to Release"
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          overwrite: true
          file_glob: true
          file: dist/*

      - name: "Publish to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
